require('plugins.colorscheme')
require('plugins.oil')
-- require('plugins.flash')
require('plugins.leap')
require('plugins.snacks')
-- require('plugins.mini_surround')
require('plugins.nvim_surround')
require('plugins.treesitter')
require('plugins.helpview')
require('plugins.lsp')
require('plugins.mini_icons')
